name: semperMade
description: Door knocking Flutter App to make it easier for going door to door and collecting data.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  responsive_framework: ^1.1.1

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
