name: semperMade
description: Medical note taking app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  equatable: ^2.0.5
  file_selector: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  gap: ^3.0.1
  get_it: ^7.6.7
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  intl: ^0.19.0
  record: ^5.0.4
  responsive_framework: ^1.1.1

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
